### ISSUE TITLE
wrong spelling of "var" tag

### ISSUE THREAD

**Issue by salvan13** [hyperapp/html#10]
https://github.com/hyperapp/html/blob/9468154855f1153e01da71869acaa18b87113689/vars.json#L101

`var` tag is wrongly spelled as `vvar`,

trying to fix it, but the build will broken since `var` is a reserverd word in js
```
[!] Error: Unexpected keyword 'var'
dist/html.js (404:16)
402: }
403: 
404: export function var(props, children) {
                     ^
405:   return vnode("var")(props, children)
406: }

```

**Comment by Swizz** [comment]
I plead guilty. That you expose is the main reason behind `vvar`.

How/Why would you use `var` ?

**Comment by JorgeBucaran** [comment]
@Swizz How to use `<var>`?

**Comment by Swizz** [comment]
`<var>` is a semantic HTML tag 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/var

**Comment by JorgeBucaran** [comment]
@Swizz And `@hyperapp/html`'s solution is to use `vvar()`?

**Comment by Swizz** [comment]
Yes. I tried `_var`, `safevar`, I am not with any of this solutions. But did not find a better one.

**Comment by JorgeBucaran** [comment]
I think `vvar` is fine. It's the best we can do.

@salvan13 I think we can close here :)

**Comment by salvan13** [comment]
why is it fine?
it produces: `<vvar></vvar>`  :scream:
which is invalid html

**Comment by Swizz** [comment]
Regarding this, yeah there is a problem :thinking:

**Comment by Swizz** [comment]
So we can remove `var` from the supported tag, and let user using `h` to use it.

Or move from an array of tag name as string to an object `[functionName]: tagString`.

**Comment by salvan13** [comment]
I think this module should support every html tags, but since it is a not very used tag and creates problems, I think we can drop it a let user using `h`, and keep the module simple as it is now.

**Comment by JorgeBucaran** [comment]
@salvan13 `var` is a reserved word, so we can't export a function `var`. I think `vvar` is a decent compromise.

**Comment by Swizz** [comment]
The function name is atm the produced tag. So it will produce `<vvar></vvar>`, I suggest to drop `var` support.
