### ISSUE TITLE
Raw styles?

### ISSUE THREAD

**Issue by brandonros** [hyperapp/html#14]
```
style({type: 'text/css'}, `body {
        position: relative;
      }

      @media (min-width: 769px) {
        .container {
          position: absolute;
          top: 50%;
          left: 50%;
          -webkit-transform: translateX(-50%) translateY(-50%);
          transform: translateX(-50%) translateY(-50%);
        }
      }

      @media (max-width: 768px) {
        .container {
          position: absolute;
          top: 50%;
          -webkit-transform: translateX(0%) translateY(-50%);
          transform: translateX(0%) translateY(-50%);
        }
      }`)
```

Doesn't work, right? Any recommendations?

**Comment by brandonros** [comment]
link does not work either.

**Comment by jorgebucaran** [comment]
@brandonros Sounds like you're looking for a CSS in JS library, not this package. This package is nothing but a function that transforms a little DSL into another one, namely `h`.

**Comment by brandonros** [comment]
You won't add valid HTML elements to an HTML library?

<link> and <style>?

**Comment by jorgebucaran** [comment]
@brandonros Seems you were looking for a Hyperapp's react-helmet or similar. There isn't one at the moment, but if you build it they will come! 😄

**Comment by brandonros** [comment]
I'm literally asking you to add two lines to https://github.com/hyperapp/html/blob/master/vars.json and publish it on npm so I can pull it in and not have to maintain my own fork of this project because they are missing in my eyes.

Why wouldn't you want to add `<link>` and `<style>`? Are they not standard or something?

**Comment by jorgebucaran** [comment]
@brandonros I think you are under the impression that adding them to `vars.json` would make any difference. Hyperapp **can't** create `<head>` or `<style>` tags and neither can React/Preact/Vue, etc.

**Comment by brandonros** [comment]
```
module.exports = function(state, actions) {
  return (

    div({style: {height: '100%'}}, [
      h('style', {type: 'text/css'}, `body {
  position: relative;
}

@media (min-width: 769px) {
  .container {
    position: absolute;
    top: 50%;
    left: 50%;
    -webkit-transform: translateX(-50%) translateY(-50%);
    transform: translateX(-50%) translateY(-50%);
  }
}

@media (max-width: 768px) {
  .container {
    position: absolute;
    top: 50%;
    -webkit-transform: translateX(0%) translateY(-50%);
    transform: translateX(0%) translateY(-50%);
  }
}`),
```

I have this code and it seems to be working fine?

**Comment by jorgebucaran** [comment]
The \<style\> tag should go inside the document's head, and the \<head\> tag should not be put inside the \<body\>. The correct solution to this issue is a CSS in JS library or hyperap-helmet.
