### ISSUE TITLE
data-foo?

### ISSUE THREAD

**Issue by brandonros** [hyperapp/html#15]
```
button({className: 'collapsed navbar-toggle', data: {target: '#navbar', toggle: 'collapse'}, type:'button'}, [
```

rends to

```
<button class="collapsed navbar-toggle" data="[object Object]" type="button">
```

Do you have an example for the syntax/is this supported?

**Comment by jorgebucaran** [comment]
@brandonros Don't use `className`, it's `class`.

As for `data`, your proposed syntax is not supported in Hyperapp, but I think it looks pretty cool. It's consistent with how [styles](https://github.com/hyperapp/hyperapp/blob/master/README.md#styles) work and how CSS class names will work in 2.0. If this is really useful I might consider adding it to Hyperapp.

You are in the wrong repo by the way. If you want to discuss this further, please [create an issue](https://github.com/hyperapp/hyperapp/issues/new) in Hyperapp.
