### ISSUE TITLE
Upgrade to latest hyperapp.

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/html#2]
Hyperapp 0.14.0 modified the VNode API from {tag,data,children} to {tag,props,children}.

- https://github.com/hyperapp/hyperapp/issues/402

**Comment by lukejacksonn** [comment]
I noticed this whilst playing around with `alpha` will bump the hyperapp version and test/pr

**Comment by Swizz** [comment]
[0.3.0](https://www.npmjs.com/package/@hyperapp/html) is now published
