### ISSUE TITLE
Allow compatibility with picodom

### ISSUE THREAD

**Issue by IamCarbonMan** [hyperapp/html#4]
Any potential for this to happen? Considering that picodom is just hyperapp's h and patch functions, it would seem the only reason this isn't compatible with hyperapp anymore is because it specifically imports hyperapp. Do we need to fork into picodom/html?

**Comment by lukejacksonn** [comment]
hummm.. good question! We used to export a factory function that allowed the developer to pass in an `h` that should be used. This makes the library much more generic but increases bundle size significantly (makes it un-tree-shakable). We could fork, but that does seem wasteful.. any bright ideas anyone?

**Comment by IamCarbonMan** [comment]
If the package was forked, would it be accepted under the NPM and Github orgs for Picodom? @JorgeBucaran

**Comment by JorgeBucaran** [comment]
@IamCarbonMan Could you create or fork/adapt the repository under your account first? I don't want to end up maintaining something I don't use. 👋😄

**Comment by IamCarbonMan** [comment]
Forked at [IamCarbonMan/picodom-html](https://github.com/IamCarbonMan/picodom-html). Basically just s/hyperapp/picodom/g.

**Comment by Swizz** [comment]
Yeah I told you, Just 3 things. I will do a review, just in case.
