### ISSUE TITLE
outdated dependency

### ISSUE THREAD

**Issue by mietennet** [hyperapp/html#6]
with # npm install @hyperapp/html

hyperapp@^0.15.0, required by @hyperapp/html@0.5.1

**Comment by Swizz** [comment]
Yeah. We need to remove the Hyperapp dependency.

**Comment by zaceno** [comment]
Is anyone working on this? @Swizz?

**Comment by JorgeBucaran** [comment]
@Swizz Can you update the dependency for now? And discuss whether we ought (probably do) depend on `hyperapp.h` or not as a separate issue? 🙏

**Comment by Swizz** [comment]
Will do.

**Comment by Swizz** [comment]
Now 1.0 is out, it requested to update dependencies and doc
