### ISSUE TITLE
HTML character entities now show properly 

### ISSUE THREAD

**Issue by willin** [hyperapp/html#7]
```js
import { h } from 'hyperapp';
import { div } from '@hyperapp/html';

export default () => (
  div({ id: 'copyright' }, 'Copyright &copy; 2002 ~ 2018')
);
// Result: Copyright &copy; 2002 ~ 2018
```

---

p.s. this way works well but i dont want to use so

```js
import { h } from 'hyperapp';
import { div } from '@hyperapp/html';

export default () => (
  div({ id: 'copyright', innerHTML: 'Copyright &copy; 2002 ~ 2018' })
);
// Result: Copyright © 2002 ~ 2018
```

**Comment by Swizz** [comment]
How about using `h` or `jsx` ?

**Comment by Swizz** [comment]
Using the following 
```jsx
const { app, h } = hyperapp
const { main, h1 } = html

/** @jsx h */

const viewHTML = (state, actions) =>
  main([
    h1({}, "Copyright &copy; 2002 ~ 2018"),
  ])

const viewJSX = (state, actions) =>
  <main>
    <h1>Copyright &copy; 2002 ~ 2018</h1>
  </main>

const viewH = (state, actions) =>
  h("main", {}, [
    h("h1", {}, "Copyright &copy; 2002 ~ 2018"),
  ])

app({}, {}, viewJSX, document.body)
```

Works as excepted only with JSX (Babel smartness ?)
So I guess this is an `h` thing.

**Comment by JorgeBucaran** [comment]
@willin The problem is with `&copy` not being rendered? Could you clarify? 🙏

**Comment by willin** [comment]
i donot want to use babel in the project because it will make the bundle file too large...

all my codes can simply in 5kb size.

**Comment by JorgeBucaran** [comment]
> I don't want to use babel in the project because it will make the bundle file too large...

I am not suggesting you use Babel, but FYI, using Babel to compile JSX into `h` will have **no** effect on your bundle size.

**Comment by willin** [comment]
er i have no idea how to figure it out

**Comment by JorgeBucaran** [comment]
@willin Problem is you write: `Copyright &copy; 2002 ~ 2018` and want `Copyright © 2002 ~ 2018` to be rendered right?

**Comment by willin** [comment]
yes

**Comment by JorgeBucaran** [comment]
@willin I'll try to figure out what's going on, in the meantime, could you just write:

```
Copyright © 2002 ~ 2018
```

Or is there a special reason you must use `&copy;`?

**Comment by willin** [comment]
hmm, almost forgot why, but i write in this way for years...

**Comment by Swizz** [comment]
It was needed for some characters to be escaped to allow safe parsing by the HTML parser. As `h` and `html` are full JS functions using sting representation escaping this characters is not longer needed (except in the case you need to make your html rendering safer aka never trust user input). 

Using JSX is not going to expand your bundle size as Babel will replace JSX tags by `h` call. I bet using JSX will be smaller than using `html`.

**Comment by JorgeBucaran** [comment]
Thanks, @Swizz. 

See:

```jsx
import React from "react";
import { render } from "react-dom";

render(
  React.createElement(
    "main",
    null,
    React.createElement("h1", null, "Copyright &copy; 2002 ~ 2018")
  ),
  document.getElementById("root")
)
```

...produces `Copyright &copy; 2002 ~ 2018`. 

@willin

**Comment by Swizz** [comment]
@JorgeBucaran Under the hood Babel is transpiling to the escaped representation too, that is why it is works with Babel.

```jsx
render(
  <main>
    <h1>Copyright &copy; 2002 ~ 2018</h1>
  </main>,
  document.getElementById("root")
)
```
is transpiled too
```jsx
render(
  React.createElement(
    "main",
    null,
    React.createElement("h1", null, "Copyright \xA9 2002 ~ 2018")
  ), 
  document.getElementById("root")
)
```
[Here is the demo](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=E4UwdgJiwBQFAAIEB4C2BDAlmAfIpKAFgIw4DCA9gA4CewmA5oQC4IBkAxtTQNwIBMABkH8EAPwGDiADmQB6EniTyM2HABp8EChwCuqcMwB0DEMwCiAGxAGwzAEI0AkhBgAiYBQrM3ASjj-QA&debug=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ces2015-loose&prettier=false&targets=&version=6.26.0)

**Comment by JorgeBucaran** [comment]
Yep.
