### ISSUE TITLE
Hyperscript helpers?

### ISSUE THREAD

**Issue by SteveALee** [hyperapp/html#9]
I found my self wanting to have hyperscript helpers (like @hyperapp/html) for the custom elements exposed here.

Does it make sense to include them in the library?

Perhaps make the html generator available as a utility so we could use it for any list of tags?

**Comment by JorgeBucaran** [comment]
I wouldn't complain if these HTML helpers were more useful out of the box. What do you have in mind?

**Comment by jorgebucaran** [comment]
@SteveALee Just in case you never got this notification. 🏓

**Comment by SteveALee** [comment]
Thanks @jorgebucaran. 

I can no longer recall what exactly I meant. It exports a helper for each HTML tag and I can't imaging what more could be more useful. I say "custom tags" but not sure what 'here' means.

Perhaps the ability to create our own helpers my provindg a list of tags?

Sorry

**Comment by jorgebucaran** [comment]
@SteveALee This package only exports the basic html tags, to create your own simply create a function.

```js
const superDiv = props => div(props)
```

Do you mean you want to see something like https://github.com/ohanhi/hyperscript-helpers here? If so, please close here and create a new issue with your API proposal. It's not the first time we've discussed this, but the problem is that:

```js
div({ id: "container", class: "jumbotron" })
```

is not any worse than

```js
div("#container.jumbotron")
```

**Comment by SteveALee** [comment]
> Do you mean you want to see something like https://github.com/ohanhi/hyperscript-helpers here?

That is very likely! And I jus tposted the wrong ref. I used those in cyclejs and liked them.

> but concluded that it is not any worse than:
> div("#container.jumbotron")

So on reflection (assuming that *was* my original thought) I agree with yo uso will close and not suggest any additions. Much better to using existing APIs.

Thanks
